import {
  BarChart,
  LineChart,
  PieChart,
  ScatterChart,
  Calendar,
  Users,
  Building2,
  BookOpen,
  Globe2,
  Hotel,
} from "lucide-react";

export const CHART_TYPES = [
  {
    id: "BAR",
    label: "Bar Chart",
    icon: BarChart,
    description: "Compare quantities across categories.",
  },
  {
    id: "LINE",
    label: "Line Chart",
    icon: LineChart,
    description: "Show trends and change over time.",
  },
  {
    id: "PIE",
    label: "Pie Chart",
    icon: PieChart,
    description: "Illustrate proportions (parts of a whole).",
  },
  {
    id: "SCATTER",
    label: "Scatter Plot",
    icon: ScatterChart,
    description: "View relationship between two variables.",
  },
];

export const DATA_TYPES = [
  // --- ACADEMIC STRUCTURE FILTERS ---
  {
    filter: "year",
    label: "Academic Session",
    type: "select",
    icon: Calendar,
    defaultValue: null, // Usually defaults to the current active session ID
    possibleValues: [
      { label: "2024/2025", value: 1 },
      { label: "2023/2024", value: 2 },
      { label: "2022/2023", value: 3 },
    ],
    note: "Fetch dynamic list from 'academic_sessions' table",
  },
  {
    filter: "STATEOFORIGIN",
    label: "State Of Origin",
    type: "select",
    icon: Globe2,
    possibleValues: [
      "Abia",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara",
    ],
  },
  {
    filter: "level",
    label: "Level",
    type: "select",
    defaultValue: null,
    possibleValues: [
      { label: "100 Level", value: 1 },
      { label: "200 Level", value: 2 },
      { label: "300 Level", value: 3 },
      { label: "400 Level", value: 4 },
      { label: "500 Level", value: 5 },
      { label: "Spillover", value: 6 },
    ],
  },
  {
    filter: "faculty",
    label: "Faculty",
    type: "select",
    defaultValue: null,
    icon: BookOpen,
    possibleValues: [
      "All",
      "Agriculture",
      "Arts",
      "Basic Medical Sciences",
      "Clinical Sciences",
      "Computing",
      "Dentistry",
      "Economics",
      "Education",
      "Environmental Design and Management",
      "Law",
      "Pharmacy",
      "Public Health",
      "Science",
      "Technology",
      "Veterinary Medicine",
    ],
    note: "Acts as a parent filter for department_id",
  },
  {
    filter: "department",
    label: "Department",
    type: "select",
    defaultValue: null,
    possibleValues: [], // Dynamic: Fetch from 'departments' table
    note: "Should be filtered based on selected faculty_id",
  },

  // --- USER DEMOGRAPHICS FILTERS ---
  {
    filter: "personnel",
    label: "Personnel",
    type: "select",
    defaultValue: "student",
    possibleValues: ["Student", "Staff"],
  },
  {
    filter: "gender",
    label: "Gender",
    icon: Users,
    type: "select",
    defaultValue: null,
    possibleValues: ["Male", "Female"],
  },
  {
    filter: "programmetype",
    label: "Programme Type",
    type: "select",
    defaultValue: "Full Time",
    possibleValues: [
      "Full Time",
      "Part Time",
      "Distance Learning",
      "Direct Entry",
    ],
  },
  {
    filter: "status",
    label: "Status",
    type: "select",
    defaultValue: null,
    possibleValues: [
      "Active",
      "Inactive",
      "Suspended",
      "Graduated",
      "Withdrawn",
    ],
  },
  // --- ACCOMMODATION / HALL FILTERS ---
  {
    filter: "hallOfResidence",
    label: "Hall of Residence",
    type: "select",
    icon: Hotel,
    defaultValue: null,
    possibleValues: [
      "Queen Elizabeth Hall",
      "Mellanby Hall",
      "King Tedder Hall",
      "Ransome Kuti Hall",
      "Sultan Bello Hall",
      "Nnamdi Azikwe Hall",
      "Independence Hall",
      "Queen Idia Hall",
      "Obafemi Awolowo Hall",
    ], // Dynamic: Fetch from 'halls' table
  },
  {
    filter: "active",
    label: "Active Only",
    type: "boolean",
    defaultValue: true,
    possibleValues: [
      { label: "Active", value: 1 },
      { label: "Inactive", value: 0 },
    ],
  },
  {
    filter: "cgm",
    label: "College of Medicine",
    type: "boolean",
    defaultValue: false,
    possibleValues: [
      { label: "Yes", value: 1 },
      { label: "No", value: 0 },
    ],
  },
];
