import {
  BarChart,
  LineChart,
  PieChart,
  ScatterChart,
  Calendar,
  Users,
  Building2,
  BookOpen,
  Globe2,
} from "lucide-react";

export const CHART_TYPES = [
  {
    id: "BAR",
    label: "Bar Chart",
    icon: BarChart,
    description: "Compare quantities across categories.",
  },
  {
    id: "LINE",
    label: "Line Chart",
    icon: LineChart,
    description: "Show trends and change over time.",
  },
  {
    id: "PIE",
    label: "Pie Chart",
    icon: PieChart,
    description: "Illustrate proportions (parts of a whole).",
  },
  {
    id: "SCATTER",
    label: "Scatter Plot",
    icon: ScatterChart,
    description: "View relationship between two variables.",
  },
];

export const DATA_TYPES = [
  {
    id: "PERSONNEL",
    label: "Personnel",
    icon: Users,
    fieldValues: [
      "Staff",
      "Student",
      "Academic Staff",
      "Non-Academic Staff",
      "Post-graduate Student",
      "Under-graduate Student",
    ],
  },
  {
    id: "GENDER",
    label: "Gender",
    icon: Users,
    fieldValues: ["Male", "Female"],
  },
  {
    id: "STATEOFORIGIN",
    label: "State Of Origin",
    icon: Globe2,
    fieldValues: [
      "Abia",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara",
    ],
  },
  {
    id: "FACULTY",
    label: "Faculty / College",
    icon: BookOpen,
    fieldValues: [
      "All",
      "Agriculture",
      "Arts",
      "Basic Medical Sciences",
      "Clinical Sciences",
      "Computing",
      "Dentistry",
      "Economics",
      "Education",
      "Environmental Design and Management",
      "Law",
      "Pharmacy",
      "Public Health",
      "Science",
      "Technology",
      "Veterinary Medicine",
    ],
  },
  {
    id: "DEPARTMENT",
    label: "Department / Programme",
    icon: Building2,
    fieldValues: [],
  },
  {
    id: "YEAR",
    label: "Academic Year",
    icon: Calendar,
    fieldValues: ["2025", "2024", "2023", "2022", "2021"],
  },
];
